import 'package:flutter/material.dart';
import 'package:marquee/marquee.dart';

class MarqueeText extends StatelessWidget {
  final String text;
  final double fontSize;
  final double blankSpace;
  final double maxWidth;

  const MarqueeText(
      {super.key,
      required this.text,
      required this.fontSize,
      required this.maxWidth,
      this.blankSpace = 15});

  @override
  Widget build(BuildContext context) {
    return calculateTextSize(text, const TextStyle(fontSize: 18)).width >
            maxWidth
        ? Marquee(
            text: text,
            style: const TextStyle(fontSize: 18),
            blankSpace: 15,
          )
        : Text(
            text,
            style: const TextStyle(fontSize: 18),
          );
  }
}

// Generated by Perplexity AI.
Size calculateTextSize(String text, TextStyle style) {
  final TextPainter textPainter = TextPainter(
    text: TextSpan(text: text, style: style),
    maxLines: 1,
    textDirection: TextDirection.ltr,
  )..layout(minWidth: 0, maxWidth: double.infinity);
  return textPainter.size;
}
